"""empty message

Revision ID: 2adae44b8cfa
Revises: 3e8910d6e68c
Create Date: 2020-08-04 18:02:10.891344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adae44b8cfa'
down_revision = '3e8910d6e68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email_server', sa.String(length=120), nullable=False),
    sa.Column('mail_ttl', sa.Boolean(), nullable=True),
    sa.Column('mail_ssl', sa.Boolean(), nullable=True),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_email_settings_email_server'), 'email_settings', ['email_server'], unique=True)
    op.create_index(op.f('ix_email_settings_username'), 'email_settings', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_settings_username'), table_name='email_settings')
    op.drop_index(op.f('ix_email_settings_email_server'), table_name='email_settings')
    op.drop_table('email_settings')
    # ### end Alembic commands ###
