"""empty message

Revision ID: 6ed95824fe3c
Revises: 2adae44b8cfa
Create Date: 2020-08-08 16:21:02.796114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ed95824fe3c'
down_revision = '2adae44b8cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_settings_email_server', table_name='email_settings')
    op.drop_index('ix_email_settings_username', table_name='email_settings')
    op.drop_table('email_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('email_server', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=False),
    sa.Column('mail_ttl', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('mail_ssl', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('creation', mysql.DATETIME(), nullable=False),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('`mail_ssl` in (0,1)', name='CONSTRAINT_2'),
    sa.CheckConstraint('`mail_ttl` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('username'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_email_settings_username', 'email_settings', ['username'], unique=True)
    op.create_index('ix_email_settings_email_server', 'email_settings', ['email_server'], unique=True)
    # ### end Alembic commands ###
