"""empty message

Revision ID: a4ee658be899
Revises: 6ed95824fe3c
Create Date: 2020-08-08 16:31:22.171560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ee658be899'
down_revision = '6ed95824fe3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_setting_email_port', table_name='email_setting')
    op.create_index(op.f('ix_email_setting_email_port'), 'email_setting', ['email_port'], unique=False)
    op.drop_index('ix_email_setting_email_server', table_name='email_setting')
    op.create_index(op.f('ix_email_setting_email_server'), 'email_setting', ['email_server'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_setting_email_server'), table_name='email_setting')
    op.create_index('ix_email_setting_email_server', 'email_setting', ['email_server'], unique=True)
    op.drop_index(op.f('ix_email_setting_email_port'), table_name='email_setting')
    op.create_index('ix_email_setting_email_port', 'email_setting', ['email_port'], unique=True)
    # ### end Alembic commands ###
